BUG FIX: undefined 'FormString::getValue(__FlashStringHelper const*)'
ld error: undefined reference to 'FormString::getValue(__FlashStringHelper const*)'
Caused by missing implementation in .cpp file.

Really it isn't necessary because Arduino String class already defines a constructor method from flash strings:  String(const __FlashStringHelper *str);
And FormString::getValue() should be a const method to avoid warning: passing 'const FormString' as 'this' argument discards qualifiers [-fpermissive]